version: '3.8'
services:
  # mysql service
  db:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '6033:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
  # node js Rest API (need to provide context)
  restapi:
    build: 
      context: nodejs-express-sequelize-mysql
      #dockerfile: DockerfileRestApi
    ports: 
      - "8080:8080"
    depends_on:
      - db
  # Angular UI application (need to provide context)
  angularapp:
    build:
      context: AngularCrud
    # start on 8081 to set the CORS policy and avoid cross origin error
    ports: 
      - "8081:8081"
    expose:
      - '8081'
    depends_on:
      - db
      - restapi
# Names our volume
volumes:
  db: